### PR TITLE
fix(resolved-view): use ResolvedViewStrategy instead of Container.inst.

### PR DESCRIPTION
**Pull request by doktordirk**
basically just copied RelativeVewStrategy over and passed on our parameters

### CODE REVIEW

**Comment by doktordirk** [comment]
@bas080 you wanted a different strategy right? now we have our own custom viewStrategy, i guess anything goes

**Comment by doktordirk** [comment]
closes https://github.com/SpoonX/aurelia-view-manager/issues/13
closes https://github.com/SpoonX/aurelia-view-manager/issues/7

load path is relative to (current file/module?) if not startting with ./ or ../

``` js
.plugin('aurelia-view-manager', config => {
      config.configure({
        'spoonx/datatable': {
          location: 'customViews/datatable.html'
        }})
    })
```

**Comment by bas080** [comment]
In case of aurelia-form it's different as it uses the resolve method and a compose element. So paths have to be relative to the `<compose>` element. Meaning that those have to stay relative.

**Comment by doktordirk** [comment]
different systems to set a path wouldn't be very user friendly. hmm

**Comment by bas080** [comment]
Maybe when one provides an absolute path (without ./) to the compose element, does it use the plugin path as base.

**Comment by doktordirk** [comment]
.plugin('aurelia-view-manager', config => {
      config.configure({
        'spoonx/datatable': {
          location: 'customViews/datatable.html'
        },
        'spoonx/form': {
            map: {
              actions: 'customViews/actions.html',
              collection: 'customViews/collection.html',
              conditional: 'customViews/conditional.html',
              select: 'customViews/select.html',
              radios: 'customViews/radios.html',
              checkboxes: 'customViews/checkboxes.html'
          }}
      })
    })

works as well (once that extend issue is fixed and if needed the references in the html itself adjusted)

**Pull request merged**
